services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project-homestay-nest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project-homestay-nest
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: npm run start:dev payment
    env_file:
      - ./apps/payment/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project-homestay-nest
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: npm run start:dev notification
    env_file:
      - ./apps/notification/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project-homestay-nest
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project-homestay-nest
    volumes:
      - .:/usr/src/app
    ports:
      - "3005:3005"
    depends_on:
      - reservations
      - auth
      - payment
      - notification
      - mongo
  mongo:
    image: mongo:latest
    container_name: reservations_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local