services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payment
      - notification
      - mongo
  reservations:
    build:
      context: ..
      dockerfile: ./apps/reservations/Dockerfile
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    build:
      context: ..
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payment:
    build:
      context: ..
      dockerfile: ./apps/payment/Dockerfile
    env_file:
      - ../apps/payment/.env
    ports:
      - '3003:3003'
  notification:
    build:
      context: ..
      dockerfile: ./apps/notification/Dockerfile
    env_file:
      - ../apps/notification/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo